#!/usr/bin/python3
#
# CLI Application to update software repositories and upgrade packages
#
# import modules
import time
import os
import sys
# defining functions
# NOTE: PUT ARCH, GENTOO, AND OTHER OS PACKAGE MANAGER'S FUNCTIONS HERE
# SEE ABOVE
# SEE ABOVE
#
# introduces the program and asks the user what os they are using
# asks the user what os they are using

# for ubuntu or debian
print("Hello, I am a basic software updater")
time.sleep(1.5)
print("Do you want to A) Update Software B) Upgrade Software C) Clean Software or All?")
time.sleep (.5)
choice = input("Enter A, B, C, or All: ")
# determining what to do
if choice == 'a':
    os.system("sudo apt-get update")
    time.sleep (1)
    print("Your repositories are up to date!")
if choice == 'A':
    os.system("sudo apt-get update")
    time.sleep (1)
    print("Your repositories is up to date!!")
if choice == 'b':
    os.system("sudo apt-get upgrade")
    time.sleep (1)
    print("Your software is up to date!!")
if choice == 'b':
    os.system("sudo apt-get upgrade")
    time.sleep (1)
    print("Your software is up to date!!")
if choice == 'B':
    os.system("sudo apt-get upgrade")
    time.sleep (1)
    print("Your software is up to date!!")
if choice == 'c':
    os.system("sudo apt-get autoremove")
    time.sleep (1)
    print("All Done!!")
if choice == 'C':
    os.system("sudo apt-get autoremove")
    time.sleep (1)
    print("All done!!")
if choice == 'all':
    os.system("sudo apt-get upgrade && sudo apt-get upgrade -y && sudo apt-get autoremove -y")
    time.sleep (1)
    print("Your system is up to date!!")
if choice == 'All':
    os.system("sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y")
    time.sleep (1)
    print("Your system is up to date!!")
# this exits the program
print("You've updated and/or cleaned your system packages.")
time.sleep (.5)
choice == input("Press 'Enter' to close the program. ")
time.sleep (1)
exec("exit()")
